### PR TITLE
Feature/request model

### PR DESCRIPTION
**Pull request by MittchoBaroco**

### CODE REVIEW

**Comment by btihen** [comment]
wierd, I had also added that you might want to consider does it make sense to make requests unique?  I am guessing no - but it is good to consider (in case they change their mind and do a different training then you need a test to be - denied doesn't count, etc.

Also - justification & concern do not need to be present, but when present they should have a certain minimum charracter lenght - pobably 5 or more characters - something like that.

**Comment by btihen** [comment]
finally - the status - the default in the db is null - do you want that?  Maybe consider starting with a "new" status - also have you considered how to validate it has a reasonable status on creation and that the changes are ok?

**Comment by btihen** [comment]
finally PO number validation should be optional - but should require at least 2 character or something like that.

**Comment by MittchoBaroco** [comment]
default status is "submitted" check migration  
t.string :status, default: "submitted", null: false

**Pull request merged**
